---
title: "Kimmo Suokas"

---

```{r}
library(magrittr)
```

Last updated: `r format(Sys.Date(), '%d.%m.%Y')`

I’m an MD, PhD, and psychiatrist with research interests in social psychiatry and psychiatric and social epidemiology.

## Study projects

### Mortalty in Mental Disorders and Genetic Liability at the Population Level: A Register-Based Study Using ICD-11

Role: Principal Investigator

This nationwide register-based study examines population-level mortality and years of life lost associated with mental disorders, accounting for diagnoses across primary and specialized healthcare, comorbidity, and genetic liability.

-   Mental disorders are harmonized using the ICD-11 classification, with diagnoses from earlier ICD versions systematically mapped to ICD-11 categories.

-   The study applies established register-based methods alongside novel approaches that capture time-varying mortality risks and genetic liability.

-   Preliminary findings suggest lower excess mortality than previously reported when all treated mental disorders are considered, providing new insights into treatment needs and healthcare system functioning.

*Funded by [The Finnish Medical Foundation](https://laaketieteensaatio.fi/en/home/) (2026).*

### Social Determinants of Mental Disorders in Finland (SDMD) – A Register-Based Study

Extended PhD project 2018-2025

A study project using national register data from the [**TRIAD**](https://thl.fi/fi/tutkimus-ja-kehittaminen/tutkimukset-ja-hankkeet/epaonnen-kolmikko-mielenterveyden-hairiot-somaattinen-sairastavuus-ja-sosiaalinen-syrjaytyminen-elamankaarella-triad-){target="_blank"} **project**, focusing on the social determinants of mental disorders in Finland.

Highlights include:

-   Interesting papers, including the publication of the year 2021 by the European Psychiatric Association (EPA)
-   An open-source method for pre-processing Finnish healthcare registers
-   My [PhD thesis](https://trepo.tuni.fi/handle/10024/153558)

[Read more](sdmd/index.html)

### Out of Despair

Role: Co-Investigator, 2023 ->

[Out of Despair](https://ulosepatoivosta.fi/en/) examines violent, suicidal, and drug-induced deaths—and near-miss cases—among young people under 30.

Key features:

-   Utilizes multiple data sources, including linked registers, qualitative interviews, mini-ethnographies, and online discussions

-   Funded by the Strategic Research Council (SRC) at the Academy of Finland

### Finnish Quality of Psychosis Care Register

Role: Co-Investigator, 2019 ->

Part of the [National quality registers in healthcare and social services](https://thl.fi/fi/web/sote-palvelujen-johtaminen/arviointi-ja-seuranta/sote-tietopohja/terveydenhuollon-kansalliset-laaturekisterit/kansallisten-laaturekisterien-raportit) in Finland, hosted by the Finnish Institute for Health and Welfare (THL).

This register monitors and improves the quality of care for individuals with psychotic disorders across the country.

### The Finnish SUPER study

Role: Co-Investigator, 2016 ->

[The Finnish SUPER study](https://www.superfinland.fi/in-english){target="_blank"} investigates the genetic mechanisms of psychotic disorders and is part of the [Stanley Global Neuropsychiatric Genomics Initiative](https://www.broadinstitute.org/stanley-center-psychiatric-research/stanley-global){target="_blank"}.

Key points:

-   Over 10 500 participants with a history of diagnosed psychotic disorders

-   Ongoing analyses of genetic and phenotypic data

-   See the [cohort profile](https://bmjopen.bmj.com/content/13/4/e070710){target="_blank"} for detailed procedures and methodology

