---
title: "Kimmo Suokas"
execute:
  echo: false
---

```{r}
library(magrittr)
library(data.table)
library(gt)

edu <- fread("../data_personal/education.csv")
pos <- fread("../data_personal/positions.csv")

```

Last updated: `r format(Sys.Date(), '%d.%m.%Y')`

## Education

```{r}

edu[order(-end_date)] %>% .[language=="en", .(years = paste0(end_date %>% year()), what = paste0("**", what, "**, ", institute))] %>%
  gt() %>% 
   fmt_markdown(columns = everything()) %>% 
  tab_options(
    table.width = pct(100),
    column_labels.hidden = TRUE,
    table.border.top.style = "hidden",
    table_body.hlines.style =  "hidden",
    table_body.border.bottom.style = "hidden"
  ) %>% 
   cols_width(
    years ~ px(120)
) %>% 
  cols_align(
    align = c("left"),
    columns = everything()
)
```

## Current work

```{r}

a <- data.table(years = 2023, what = '**Researcher, [Psychosocial Factors and Health - study group](https://www.helsinki.fi/en/researchgroups/psychosocial-factors-and-health)**', where = 'Department of Psychology and Logopedics, Faculty of Medicine, University of Helsinki.')


b <- data.table(years = 2023, what = '**Consultant Psychiatrist**', where = '[Psykiatrikonsultaatiot Hilla Oy and Mehiläinen](https://www.hillaoy.fi)')

c <- data.table(years = 2019, what = '**Project Worker at the [Finnish Psychiatric Association](https://www.psy.fi/in_english)**', where = 'Member at the [Finnish Quality of Psychosis Care Register](https://repo.thl.fi/sites/laaturekisterit/psykoosienhoidonrekisteri.html) -team at the [National quality registers in healthcare and socialservices](https://thl.fi/fi/web/sote-palvelujen-johtaminen/arviointi-ja-seuranta/sote-tietopohja/terveydenhuollon-kansalliset-laaturekisterit/kansallisten-laaturekisterien-raportit) -project at the [Finnish Institute for Health and Welfare (THL)](https://thl.fi/en/web/thlfi-en)')

rbindlist(list(a, b, c), idcol = "item") %>% .[,.(years = paste0(years, " ->"), what =paste0(what, " <br> ", where))] %>% 
  gt() %>% 
   fmt_markdown(columns = everything()) %>% 
  tab_options(
    table.width = pct(100),
    column_labels.hidden = TRUE,
    table.border.top.style = "hidden",
    table_body.hlines.style =  "hidden",
    table_body.border.bottom.style = "hidden"
  ) %>% 
   cols_width(
    years ~ px(120)
) %>% 
  cols_align(
    align = c("left"),
    columns = everything()
) %>% 
    tab_style(
    style = "vertical-align:top",
    locations = cells_body(
      columns = years
      )
  ) 
```


## Awards

```{r}

list(
  data.table(years = 2025, what = '**Martti Kaila Award** for an Outstanding Doctoral Dissertation in 2024 by the [Finnish Psychiatric Association](https://psy.fi/martti-kaila-palkinto-2024/)'),
  data.table(years = 2025, what = 'University of Tampere Foundation Grant for a doctoral dissertation accepted with distinction 2025'),
  data.table(years = 2021, what = '[Research Prize](https://www.europsy.net/previous-winners/) by the European Psychiatric Association (EPA)'),
  data.table(years = 2020, what = '**Publication of the Year** award by the Finnish Psychiatric Association')) %>% 
  rbindlist() %>% 
   gt() %>% 
   fmt_markdown(columns = everything()) %>% 
  tab_options(
    table.width = pct(100),
    column_labels.hidden = TRUE,
    table.border.top.style = "hidden",
    table_body.hlines.style =  "hidden",
    table_body.border.bottom.style = "hidden"
  ) %>% 
   cols_width(
    years ~ px(120)
) %>% 
  cols_align(
    align = c("left"),
    columns = everything()
) %>% 
  tab_style(
    style = "vertical-align:top",
    locations = cells_body(
      columns = years
      )
  ) 


```


## Past work

```{r}
a <- pos[language=="en" & !is.na(end_date), .(years = ifelse(year(start_date) == year(end_date), year(start_date),  paste0(year(start_date), "--", year(end_date))), item = paste0("<b>",what, "</b><br>", where, "<br>", details_1))] %>% head(-6) 
b <- data.table(years = c("2011--2018"), item = paste0("**Specialising Physician** at ", pos[language == "en"] %>% 
  tail(6) %>% 
  .$where %>% 
  paste(collapse = '; ')))

rbindlist(list(a, b)) %>% 
  gt() %>% 
   fmt_markdown(columns = everything()) %>% 
  tab_options(
    table.width = pct(100),
    column_labels.hidden = TRUE,
    table.border.top.style = "hidden",
    table_body.hlines.style =  "hidden",
    table_body.border.bottom.style = "hidden"
  ) %>% 
   cols_width(
    years ~ px(120)
) %>% 
  cols_align(
    align = c("left"),
    columns = everything()
) %>% 
  tab_style(
    style = "vertical-align:top",
    locations = cells_body(
      columns = years
      )
  ) 



```
