---
title: "Social determinants of mental disorders in Finland - a register-based study"
execute:
  echo: false
---

```{r}
library(magrittr)
library(data.table)
library(gt)

awards <- fread("../data_personal/awards.csv") %>% .[language == "en"]

pubs <- fread("../publications/publications.csv")

```

Last updated: `r format(Sys.Date(), '%d.%m.%Y')`

## Aims

This project aims to:

-   update key descriptive analyses of the epidemiology of mental disorders in Finland, incorporating both primary and secondary care data;
-   examine the dynamic interplay between socioeconomic factors and mental health across the life course and on multiple levels; and
-   improve the conditions and methodologies of register-based research by applying principles of open science.

## Rationale

Although analytical epidemiology has advanced our understanding of mental disorders, descriptive analysis remains essential for capturing the broader landscape of psychiatry and mental health. Trends such as deinstitutionalization, evolving public attitudes, the integration of mental health into primary care, and socio-political changes highlight the need for regularly updated descriptive data and continuous monitoring.

These efforts are crucial not only for informing clinicians and the public but also for fostering evidence-based discussions about best practices in mental health care.

Depression and anxiety are among the ten most common reasons for visits to primary care in Finland. Yet, much of the existing register-based research focuses exclusively on secondary care. This project seeks to address this gap by analyzing both primary and secondary mental health service use.

So far, this project has focused on several classical questions in psychiatric epidemiology:

## Topics

### Lifetime incidence, age of onset, and 12-month service utilization related to mental disorders in primary and secondary care

This study is the first to utilize both primary and secondary nationwide administrative health care data in Finland to examine the prevalence of diagnosed mental disorders.

The lifetime incidence of any diagnosed mental disorder by age 100 was 76.7% in women and 69.7% in men.

Using stricter criteria—focusing only on non-organic mental disorders (ICD-10: F10–F99)—the lifetime incidence at age 75 was 65.6% for women and 60.0% for men (95% CI: 59.9–60.1).

These estimates are somewhat lower than comparable figures from Denmark and New Zealand.
#### Reference

-   `r pubs[reference %like% "10.1017/s2045796025100061", ref_link]`

#### Media

-   [Press release](https://www.helsinki.fi/fi/uutiset/vaeston-terveys/mielenterveyden-hairiot-koskettavat-valtaosaa-suomalaisista)
-   [Valtaosa suomalaisista saa mielenterveyshäiriön diagnoosin](https://yle.fi/a/74-20169733). YLE
-   [Yli 70 prosenttia suomalais­naisista saa diagnoosin elämänsä aikana, kertoo tuore tutkimus](https://www.hs.fi/tiede/art-2000011326509.html). HS
-   [Noin 77 prosenttia suomalaisista naisista saa diagnoosin mielenterveyshäiriöön elämänsä aikana – poikien ensimmäinen diagnoosi usein jo kuusivuotiaana](https://www.ksml.fi/uutissuomalainen/8637126) Keskisuomalainen
-   [Yli 70 prosenttia naisista saa tämän diagnoosin](https://www.iltalehti.fi/mielijamasennus/a/a535dbbe-44dc-4395-b2ec-fc5de9a0ee7d) Iltalehti
-   [Mielenterveyden häiriöt koskettavat valtaosaa suomalaisista](https://www.laakarilehti.fi/terveydenhuolto/mielenterveyden-hairiot-koskettavat-valtaosaa-suomalaisista/) Lääkärilehti

### Household income and the incidence of first psychiatric hospital admissions

This study is among the few that report incidence rates for all first psychiatric hospital admissions. To the best of our knowledge, it is also the first national-level study to demonstrate a clear income gradient in the incidence of first hospitalizations due to mental disorders. Household income emerged as a significant risk factor across the entire income distribution.

In Finland, between 1994 and 2014, the age-standardized annual incidence rate of first psychiatric hospital admissions peaked in 2008 and declined thereafter.

Following this study, two other Finnish publications reported similar trends, including increases in first admissions among adolescents and among children, adolescents, and young adults. These findings are particularly noteworthy in the context of a health care system increasingly oriented toward outpatient care. The observed increase in first hospitalizations raises concerns about the effectiveness of outpatient services in preventing or managing acute and severe mental health crises.
#### Awards

This study won the Publication of the Year by `r awards[what == "Publication of the Year", paste(by_whom, "in", years)]` and the `r awards[by_whom %like% "EPA", paste0(what, " by the ", by_whom, " in ", years)]` awards.

#### References

-   `r pubs[reference %like% "10.1001/jamapsychiatry.2019.3647", ref_link]`

#### Media (mainly in Finnish)

-   [Press release](https://www.tuni.fi/fi/ajankohtaista/tulojen-ja-ensimmaisen-psykiatrisen-sairaalahoidon-valilla-selva-yhteys)
-   [Tutkimus: Köyhät päätyvät rikkaampia useammin psykiatriseen sairaalahoitoon](https://yle.fi/a/3-11129680). YLE
-   [Analyysi: Mielen hyvinvoinnin tukeminen on osa kasautuvan huono-osaisuuden ehkäisyä](https://kuntalehti.fi/uutiset/sote/analyysi-mielen-hyvinvoinnin-tukeminen-on-osa-kasautuvan-huono-osaisuuden-ehkaisya/). Kuntalehti

### Regional and urban-rural variations in the prevalence of mental disorders

In Finland, the prevalence of schizophrenia has traditionally been higher in the eastern and northern regions, mirroring the distribution of schizophrenia polygenic risk scores. Both genetic and environmental factors have been suggested as contributors to this regional variation, which aligns with a well-established east–west gradient in population health and genetic structure.

However, in our study, after adjusting for socioeconomic and sociodemographic factors, this east–west pattern in the prevalence of mental disorders largely disappeared. In contrast, urban–rural differences remained robust, even after adjustment.

#### References

-   `r pubs[reference %like% "10.1007/s00127-023-02516-x", ref_link]`

#### Media

-   [Press release](https://www.tuni.fi/fi/ajankohtaista/mielenterveyshairiot-yleisempia-kaupungeissa-korkeammasta-tulotasosta-huolimatta)
-   [Ennen psykooseja esiintyi Suomessa enemmän maaseudulla kuin kaupungeissa – ei enää, sanoo uusi tutkimus](https://www.hameensanomat.fi/uutissuomalainen/6018026). Hämeen Sanomat
-   [Ennen psykooseja esiintyi Suomessa enemmän maaseudulla kuin kaupungeissa – ei enää, sanoo uusi tutkimus](https://www.ess.fi/uutissuomalainen/6018026). Etelä-Suomen Sanomat
-   [Asetelma kääntyi Suomessa: mielenterveyden häiriöitä esiintyy enemmän kaupungeissa kuin maaseudulla](https://www.kainuunsanomat.fi/artikkeli/asetelma-kaantyi-suomessa-mielenterveyden-hairioita-esiintyy-enemman-kaupungeissa-kuin-maaseudulla). Kainuun Sanomat
-   [Tampereen yliopiston tutkimus: psykooseja ja muita mielenterveyden häiriöitä esiintyy eniten kaupungeissa](https://www.aamulehti.fi/kotimaa/art-2000009669630.html). Aamulehti

### Excess mortality related to mental disorders

Excess mortality among people with mental disorders is a well-documented phenomenon, but most previous studies have focused exclusively on individuals treated in secondary care settings.

By including individuals treated in both primary and secondary care, our study found substantially lower estimates of excess mortality compared to analyses limited to secondary care data. Notably, the majority of individuals with recently treated mental disorders had contact only with primary care services.

These findings refine the established view of dramatically reduced life expectancy among people with mental disorders. While excess mortality remains a serious concern, the inclusion of primary care data offers a more nuanced and less pessimistic perspective on the burden of mental disorders—highlighting their heterogeneity in the population.

To the best of our knowledge, this is the first nationwide study to examine mortality among individuals with treated mental disorders using both primary and secondary care data.

#### References

-   `r pubs[reference %like% "10.1002/wps.21027", ref_link]`
-   `r pubs[ref_link %like% "duo17158", ref_link]` Invited editorial.

#### Media

-   [Press release](https://www.sttinfo.fi/tiedote/69960285/mielenterveyden-hairioihin-liittyva-kuolleisuus-on-aiemmin-arvioitua-vahaisempaa?publisherId=69818730)
-   [Mielenterveyden häiriöihin liittyvä kuolleisuus on arvioitua vähäisempää](https://www.laakarilehti.fi/terveydenhuolto/mielenterveyden-hairioihin-liittyva-kuolleisuus-on-arvioitua-vahaisempaa/). Lääkärilehti

## Data and methodology

National registers from [TRIAD](https://thl.fi/fi/tutkimus-ja-kehittaminen/tutkimukset-ja-hankkeet/epaonnen-kolmikko-mielenterveyden-hairiot-somaattinen-sairastavuus-ja-sosiaalinen-syrjaytyminen-elamankaarella-triad-){target="_blank"}: The unhappy triad - Mental disorders, somatic illness and socioeconomic deprivation in different phases of life - project have been used.

### Pre-processing of the register: Identifying treamtment episodes

The scripts called [hilmo_identify_episodes](https://github.com/kmmsks/hilmo_identify_episodes) have been made publicly available in order to enable others to evaluate and benefit from this effort. We call for open science principles and collaborative development of readily available methods for saving researchers' time and enhancing research quality by improving comparability and reproducibility of results.

In this study, we showed that registers with continuous and mainly automatized data collection, such as the Finnish healthcare registers, contain partly overlapping register entries and preliminary diagnoses. The methods employed in pre-processing register data significantly impact the metrics derived from the registers. Regarding lifetime incidence of mental disorders, schizophrenia spectrum disorders require a particular focus on data pre-processing.

#### References:

-   Suokas, K.,  Gutvilig, M.,  Lumme, S.,  Pirkola, S., &  Hakulinen, C. (2024).  Enhancing the accuracy of register-based metrics: Comparing methods for handling overlapping psychiatric register entries in Finnish healthcare registers. *International Journal of Methods in Psychiatric Research*, e2029. <https://doi.org/10.1002/mpr.2029>

-   Suokas, K (2023). hilmo_identify_episodes (v2.0.0) \[Source code\]. <https://github.com/kmmsks/hilmo_identify_episodes>. doi: [10.5281/zenodo.4095153](https://zenodo.org/records/10171088).

## My PhD thesis

[Link](https://trepo.tuni.fi/handle/10024/153558) to the thesis document.

The thesis was granted the Martti Kaila Award for an Outstanding Doctoral Dissertation 2024 by the Finnish Psychiatric Association ([link](https://psy.fi/martti-kaila-palkinto-2024/)) and and received a University of Tampere Foundation Grant for a doctoral dissertation accepted with distinction.

### Media

-   [Rekisteritieto päivittää perustietämystä väestön mielenterveyshäiriöistä](https://www.tuni.fi/fi/ajankohtaista/kimmo-suokas-rekisteritieto-paivittaa-perustietamysta-vaeston-mielenterveyshairioista). Tampereen yliopisto: tiedote.

-   [Tutkija löysi yllättävää uutta tietoa Suomen mielenterveyspotilaista: kuolleisuus luultua vähäisempää, itä eroaa lännestä](https://yle.fi/a/74-20081831). Yle

-   [Mielenterveyden häiriöihin liittyvä kuolleisuus arvioitua vähäisempää](https://www.laakarilehti.fi/tieteessa/mielenterveyden-hairioihin-liittyva-kuolleisuus-arvioitua-vahaisempaa/) Suomen Lääkärilehti.
